--CREATE DATABASE SieuThi
USE SieuThi
Go

create table USERS(
	USERNAME varchar(40) primary key,
	PASS varchar(30),
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(6), 
	EMAIL varchar(50),
	QUYEN int check(QUYEN=1 or QUYEN=0),--PHÂN QUYỀN VỚI ADMIN VÀ KHÁCH HÀNG
)
GO
CREATE TABLE HANGHOA(
	MASANPHAM VARCHAR(8) PRIMARY KEY,
	TENSANPHAM NVARCHAR(50) UNIQUE,
	SOLUONG INT,
	GIANHAPVAO INT,
	GIABANRA INT,
	NGAYNHAP DATE,
	KIEMTRALOI BIT,--KIỂM TRA SẢN PHẨM LỖI HAY K
)
GO
CREATE TABLE KHUYENMAI(
	MAKHUYENMAI VARCHAR(8) PRIMARY KEY,
	TENKHUYENMAI NVARCHAR(30),
	PHANTRAM INT CHECK (PHANTRAM>=0 AND PHANTRAM<=100),
	NGAYKHUYENMAI DATE,
)
GO
CREATE TABLE DONHANG(
	MADONHANG VARCHAR(8) NOT NULL,
	MASANPHAM VARCHAR(8) references HANGHOA(MASANPHAM) NOT NULL,
	USERNAME VARCHAR(40) REFERENCES USERS(USERNAME),
	TENDONHANG NVARCHAR(30),
	MAKHUYENMAI VARCHAR(8) REFERENCES KHUYENMAI(MAKHUYENMAI),
	XACNHAN INT, --ĐƠN HÀNG ĐƯỢC ADMIN BAN TAI CHO=1, CHƯA DUYỆT =0, ĐÃ GIAO =2,KHACH TRA = 3
	NGAYDAT DATE,
	NGAYGIAOHANG DATE,
	PRIMARY KEY(MADONHANG,MASANPHAM)
)
go
CREATE VIEW VIEW_KHACHHANG AS
( SELECT B1.*,B2.SOLUONGHANGMUA,B2.TONGSOTIEN FROM dbo.USERS AS B1,(SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA,SUM(GIABANRA) AS TONGSOTIEN FROM 
(SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM) AS TEMP 
GROUP BY USERNAME) AS B2 
WHERE B1.USERNAME=B2.USERNAME
)
GO
--SELECT * FROM VIEW_KHACHHANG
GO
CREATE VIEW VIEW_DONHANG AS (
SELECT a.MADONHANG,b.TENSANPHAM,a.USERNAME,a.TENDONHANG,a.MAKHUYENMAI,a.XACNHAN,a.NGAYDAT,a.NGAYGIAOHANG 
FROM dbo.DONHANG AS a,dbo.HANGHOA AS b 
WHERE a.MASANPHAM= b.MASANPHAM
)

GO
--SELECT * FROM dbo.VIEW_DONHANG
-----------------------------Data-------------------------

INSERT INTO USERS VALUES('quanghai142','14020501',N'Trương Quang Hải','Nam','quanghai14297@gmail.com','0')
INSERT INTO USERS VALUES('admin','1',N'Trương Quang Hải','Nam','quanghai14@gmail.com','0')
INSERT INTO USERS VALUES('gianghai','1',N'Giang Văn Hải','Nam','gianghai@gmail.com','0')
INSERT INTO USERS VALUES('lehiep','1',N'Lê Hoàng Hiệp','Nam','lehiep@gmail.com','0')
--select * from users
insert into HANGHOA VALUES('SP151462','TIVI SAMSUNG',6,'20000','50000','20180207',0)
insert into HANGHOA VALUES('SP151463','TIVI LG',6,'20000','50000','20180207',0)
insert into HANGHOA VALUES('SP151464','NOI COM COOKU',6,'10000','12000','20180402',0)
insert into HANGHOA VALUES('SP151465','DIEU HOA PANASONIC',6,'15000','18000','20180402',0)
insert into HANGHOA VALUES('SP151466','TU LANH SAMSUNG',6,'20000','25000','20180402',0)
insert into HANGHOA VALUES('SP151467','LAPTOP SAMSUNG',6,'20000','25000','20180402',0)
insert into HANGHOA VALUES('SP151410','IPX',6,'22000','25000','20180402',0)

INSERT INTO KHUYENMAI VALUES('KM_8/3','NGÀY 8-3','70','20180308')
INSERT INTO KHUYENMAI VALUES('KM_1/5','NGÀY 1-5','70','20180501')

INSERT INTO DONHANG VALUES('DH162877','SP151462','quanghai142',N'ĐIỆN TỬ','KM_8/3',1,'20180330','20180426')
INSERT INTO DONHANG VALUES('DH162873','SP151463','quanghai142',N'ĐIỆN TỬ','KM_1/5',1,'20180226','20180426')


------------------------Nháp---------------------------

SELECT MAX(MADONHANG) FROM dbo.DONHANG
--SELECT * FROM dbo.USERS,
SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA FROM dbo.DONHANG GROUP BY USERNAME
SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM

SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA,SUM(GIABANRA) AS TONGSOTIEN FROM 
(SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM) AS TEMP 
GROUP BY USERNAME

SELECT B1.*,B2.SOLUONGHANGMUA,B2.TONGSOTIEN FROM dbo.USERS AS B1,(SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA,SUM(GIABANRA) AS TONGSOTIEN FROM 
(SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM) AS TEMP 
GROUP BY USERNAME) AS B2 
WHERE B1.USERNAME=B2.USERNAME

INSERT INTO dbo.DONHANG
VALUES  ( '' , -- MADONHANG - varchar(8)
          '' , -- MASANPHAM - varchar(8)
          '' , -- USERNAME - varchar(40)
          N'' , -- TENDONHANG - nvarchar(30)
          '' , -- MAKHUYENMAI - varchar(8)
          0 , -- XACNHAN - int
          GETDATE() , -- NGAYDAT - date
          GETDATE()  -- NGAYGIAOHANG - date
        )