--CREATE DATABASE SieuThi
USE SieuThi
Go

create table USERS(
	USERNAME varchar(40) primary key,
	PASS varchar(30),
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(6), 
	EMAIL varchar(50),
	QUYEN int check(QUYEN=1 or QUYEN=0 OR QUYEN=2),--PHÂN QUYỀN VỚI ADMIN VÀ KHÁCH HÀNG
	Del BIT
)
GO
CREATE TABLE HANGHOA(
	MASANPHAM VARCHAR(8) PRIMARY KEY,
	TENSANPHAM NVARCHAR(50),
	SOLUONG INT,
	GIANHAPVAO INT,
	GIABANRA INT,
	NGAYNHAP DATE,
	Del BIT,--KIỂM TRA SẢN PHẨM LỖI HAY K
)
ALTER TABLE dbo.HANGHOA DROP CONSTRAINT UQ__HANGHOA__F0738286A7E65CC0
GO
CREATE TABLE KHUYENMAI(
	MAKHUYENMAI VARCHAR(8) PRIMARY KEY,
	TENKHUYENMAI NVARCHAR(30),
	PHANTRAM INT CHECK (PHANTRAM>=0 AND PHANTRAM<=100),
	NGAYKHUYENMAI DATE,
	Del BIT
)
GO
CREATE TABLE DONHANG(
	MADONHANG VARCHAR(8) NOT NULL,
	MASANPHAM VARCHAR(8) references HANGHOA(MASANPHAM) NOT NULL,
	USERNAME VARCHAR(40) REFERENCES USERS(USERNAME),
	TENDONHANG NVARCHAR(30),
	MAKHUYENMAI VARCHAR(8) REFERENCES KHUYENMAI(MAKHUYENMAI),
	XACNHAN INT, --ĐƠN HÀNG ĐƯỢC ADMIN BAN TAI CHO=1, CHƯA DUYỆT =0, ĐÃ GIAO =2,KHACH TRA = 3
	NGAYDAT DATE,
	NGAYGIAOHANG DATE,
	SOLUONG INT,
	PRIMARY KEY(MADONHANG,MASANPHAM)
)
go
CREATE VIEW VIEW_KHACHHANG AS
( SELECT B1.*,B2.SOLUONGHANGMUA,B2.TONGSOTIEN FROM dbo.USERS AS B1,(SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA,SUM(GIABANRA) AS TONGSOTIEN FROM 
(SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM) AS TEMP 
GROUP BY USERNAME) AS B2 
WHERE B1.USERNAME=B2.USERNAME
)
GO
--SELECT * FROM VIEW_KHACHHANG
GO
CREATE VIEW VIEW_DONHANG1 AS (
SELECT a.MADONHANG,b.TENSANPHAM,a.USERNAME,a.TENDONHANG,a.MAKHUYENMAI,a.XACNHAN,a.NGAYDAT,a.NGAYGIAOHANG 
FROM dbo.DONHANG AS a,dbo.HANGHOA AS b 
WHERE a.MASANPHAM= b.MASANPHAM
)
GO
CREATE VIEW VIEW_DONHANG AS(
SELECT a.MADONHANG,b.TENSANPHAM,a.USERNAME,a.TENDONHANG,a.MAKHUYENMAI,a.NGAYDAT,a.NGAYGIAOHANG 
FROM dbo.DONHANG AS a, dbo.HANGHOA AS b
WHERE a.MASANPHAM=b.MASANPHAM)
GO
--SELECT * FROM dbo.VIEW_DONHANG
-----------------------------Data-------------------------

INSERT INTO USERS VALUES('quanghai142','14020501',N'Trương Quang Hải','Nam','quanghai14297@gmail.com','0')
INSERT INTO USERS VALUES('admin','1',N'Trương Quang Hải','Nam','quanghai14@gmail.com','0')
INSERT INTO USERS VALUES('gianghai','1',N'Giang Văn Hải','Nam','gianghai@gmail.com','0')
INSERT INTO USERS VALUES('lehiep','1',N'Lê Hoàng Hiệp','Nam','lehiep@gmail.com','0')
--select * from users
insert into HANGHOA VALUES('SP151462','TIVI SAMSUNG',6,'20000','50000','20180207',0)
insert into HANGHOA VALUES('SP151463','TIVI LG',6,'20000','50000','20180207',0)
insert into HANGHOA VALUES('SP151464','NOI COM COOKU',6,'10000','12000','20180402',0)
insert into HANGHOA VALUES('SP151465','DIEU HOA PANASONIC',6,'15000','18000','20180402',0)
insert into HANGHOA VALUES('SP151466','TU LANH SAMSUNG',6,'20000','25000','20180402',0)
insert into HANGHOA VALUES('SP151467','LAPTOP SAMSUNG',6,'20000','25000','20180402',0)
insert into HANGHOA VALUES('SP151410','IPX',6,'22000','25000','20180402',0)

INSERT INTO KHUYENMAI VALUES('KM_8/3','NGÀY 8-3','70','20180308')
INSERT INTO KHUYENMAI VALUES('KM_1/5','NGÀY 1-5','70','20180501')

INSERT INTO DONHANG VALUES('DH162877','SP151462','quanghai142',N'ĐIỆN TỬ','KM_8/3',1,'20180330','20180426')
INSERT INTO DONHANG VALUES('DH162873','SP151463','quanghai142',N'ĐIỆN TỬ','KM_1/5',1,'20180226','20180426')


------------------------Nháp---------------------------

SELECT MAX(MADONHANG) FROM dbo.DONHANG
--SELECT * FROM dbo.USERS,
SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA FROM dbo.DONHANG GROUP BY USERNAME
SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM

SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA,SUM(GIABANRA) AS TONGSOTIEN FROM 
(SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM) AS TEMP 
GROUP BY USERNAME

SELECT B1.*,B2.SOLUONGHANGMUA,B2.TONGSOTIEN FROM dbo.USERS AS B1,(SELECT USERNAME,COUNT(MASANPHAM) AS SOLUONGHANGMUA,SUM(GIABANRA) AS TONGSOTIEN FROM 
(SELECT A.*,B.GIABANRA FROM dbo.DONHANG AS A, dbo.HANGHOA AS B WHERE A.MASANPHAM=B.MASANPHAM) AS TEMP 
GROUP BY USERNAME) AS B2 
WHERE B1.USERNAME=B2.USERNAME

INSERT INTO dbo.DONHANG
VALUES  ( '' , -- MADONHANG - varchar(8)
          '' , -- MASANPHAM - varchar(8)
          '' , -- USERNAME - varchar(40)
          N'' , -- TENDONHANG - nvarchar(30)
          '' , -- MAKHUYENMAI - varchar(8)
          0 , -- XACNHAN - int
          GETDATE() , -- NGAYDAT - date
          GETDATE()  -- NGAYGIAOHANG - date
        )
--------------PROC------------------
GO
ALTER PROCEDURE SID_DONHANG(
@MADON VARCHAR(8),
@MASP VARCHAR(8),
@USERNAME VARCHAR(40),
@TENDONHANG NVARCHAR(30),
@MAKM VARCHAR(8),
@DATHANG DATE,
@GIAOHANG DATE,
@Statement VARCHAR(10)=''
) AS 
BEGIN
	IF @Statement = 'Selecct'
	BEGIN
		SELECT * FROM dbo.DONHANG WHERE MADONHANG=@MADON AND MASANPHAM=@MASP
	END
	IF @Statement = 'Insert'
	BEGIN
		INSERT INTO dbo.DONHANG
		VALUES  ( @MADON , -- MADONHANG - varchar(8)
		          @MASP , -- MASANPHAM - varchar(8)
		          @USERNAME , -- USERNAME - varchar(40)
		          @TENDONHANG , -- TENDONHANG - nvarchar(30)
		          @MAKM , -- MAKHUYENMAI - varchar(8)
		          @DATHANG , -- NGAYDAT - date
		          @GIAOHANG  -- NGAYGIAOHANG - date
		        )
	END
	IF @Statement = 'Delete'
	BEGIN
		DELETE FROM dbo.DONHANG WHERE MADONHANG=@MADON AND MASANPHAM=@MASP
	END
END
GO
EXECUTE dbo.SID_DONHANG '','','',N'','','','',''
GO
ALTER PROCEDURE UID_HANGHOA(
@maSP VARCHAR(8),
@tenSP NVARCHAR(50),
@soluong INT,
@giaNhap INT,
@giaBan INT,
@ngayNhap DATE,
@Statement NVARCHAR(20)=''
) AS
BEGIN
	IF @Statement ='Select'
	BEGIN
		SELECT * FROM dbo.HANGHOA WHERE MASANPHAM=@maSP
	END
	IF @Statement='Insert'
	BEGIN
		INSERT INTO dbo.HANGHOA VALUES  (
				@maSP , -- MASANPHAM - varchar(8)
		        @tenSP , -- TENSANPHAM - nvarchar(50)
		        @soluong , -- SOLUONG - int
		        @giaNhap , -- GIANHAPVAO - int
		        @giaBan , -- GIABANRA - int
		        @ngayNhap , -- NGAYNHAP - date
		        0  -- IsDel - bit
				)
	END
	IF @Statement='Update'
	BEGIN
		UPDATE dbo.HANGHOA SET 
		TENSANPHAM=@tenSP,
		SOLUONG=@soluong,
		GIANHAPVAO=@giaNhap,
		GIABANRA=GIABANRA,
		NGAYNHAP=@ngayNhap
		WHERE MASANPHAM=@maSP
	END
	IF @Statement='Hide'
	BEGIN
		UPDATE dbo.HANGHOA SET IsDel=1 WHERE MASANPHAM=@maSP
	END
	IF @Statement = 'Delete'
	BEGIN
		DELETE FROM dbo.DONHANG WHERE MASANPHAM=@maSP
		DELETE FROM dbo.HANGHOA WHERE MASANPHAM=@maSP
	END
END
GO
EXECUTE dbo.UID_HANGHOA '',N'',0,0,0,'',N''
